### ISSUE TITLE
Error report: e.replace is not a function

### ISSUE THREAD

**Issue by willbasky** [notable/dumper#23]
- **OS Version**: linux 4.15.0-66-generic
- **Notable Version**: v1.8.1

```
TypeError: e.replace is not a function
    at Function.decode [as default] (file:///tmp/.mount_NotabloQy14L/resources/app.asar/renderer/renderer.js:2:156894)
    at EnexNote.sanitizeMetadata (file:///tmp/.mount_NotabloQy14L/resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:7328)
    at EnexNote.get (file:///tmp/.mount_NotabloQy14L/resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:6782)
    at async EnexProvider.dump (file:///tmp/.mount_NotabloQy14L/resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:6690)
    at async Object.dump (file:///tmp/.mount_NotabloQy14L/resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:58984)
    at async import_Import.import (file:///tmp/.mount_NotabloQy14L/resources/app.asar/renderer/renderer.js:2:22114)
```

**Comment by fabiospampinato** [comment]
@willbasky Could you post an `enex` file that reproduce the error? You could also send it to me directly at fabio@notable.md

**Comment by willbasky** [comment]
@fabiospampinato I guess no, it contents personal notes :)

**Comment by fabiospampinato** [comment]
@willbasky Sure, I understand. Could you try then to find the note that causes the problem and they try making a similar mock one that reproduces the problem? I think this is most probably related to the tags a note has been tagged, so the actual content of the note is not important.

**Comment by willbasky** [comment]
I export from enex with tags off. Notable imported the same sum of notes. 
I tried to export import note that didn't imported on previous attempt and it imported.
It hard to find note among > 900 of them by hand.

**Comment by fabiospampinato** [comment]
I'll see if I can reproduce this myself, thanks for reporting the error!
